sudo: required
dist: trusty

language: node_js
node_js:
  - "9.3.0"

matrix:
  fast_finish: true

notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - free30murgh@gmail.com

cache:
  directories:
    - node_modules

before_install:
  - npm install -g create-react-native-app

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - export CI=false
  - cp src/env.sample.json src/env.json

script:
  - yarn run relay
  - yarn run lint
  - ./cc-test-reporter before-build
  - yarn test --maxWorkers=4

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
